### PR TITLE
Fix decoding of enum with associated values when enum case does not contain value

### LINKED ISSUE #202: How to encode empty tags as enum based on name
Hey, at first thanks a lot for making this library, great work! 

I am rather new to the XML game and trying to decode WebDAV responses. 
So I have the following response from the server: 

```xml
<?xml version="1.0" standalone="yes"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <d:response>
        <d:href>someURL</d:href>
        <d:propstat>
            <d:prop>
                <d:resourcetype>
                    <d:collection></d:collection>
                </d:resourcetype>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

And the following `Codable` models: 

```swift
struct MultiStatus: Codable {
    let responses: [MultiStatusResponse]
    
    enum CodingKeys: String, CodingKey {
        case responses = "response"
    }
}

struct MultiStatusResponse: Codable {
    struct Property: Codable {
        enum ResourceType: Codable {
            case collection
            case file
            case redirect
        }
        
        let ressourceType: ResourceType
    }

    let href: String
    let properties: [Property]
    let error: String?
    
    enum CodingKeys: String, CodingKey {
        case href
        case properties = "prop"
        case error
    }
}
```
-> This implementation does not work, because it is complaining about the `ResourceType` enum not conforming to `Codable` because of the missing  method implementations of `decode` and `encode`.

I am searching for a way to decode the 
```xml
  <d:resourcetype>
      <d:collection></d:collection>
  </d:resourcetype>
```
part into an enum case based on the tag inside the `<d:resourcetype>` tag. So in this case I would like the `ResourceType` enum to be of case `collection`. Is that possible with your library or do I need to go one level deeper and parse the XML by myself ? I tried to write custom `decode` and `encode` methods but unfortunately didn't get it to work.

### PR DESCRIPTION
**Pull request by Alkenso**
Consider enum with associated values, where some value is empty
```
enum Choice: Equatable, Codable {
      case one
      case two(Int)
      case three(String, value: Int)
}
```

This PR fix decoding of such enum (while encoding is already worked as expected)
See new test in commit for details

Seems it also fixes #202

### CODE REVIEW

**Comment by Alkenso** [comment]
@johankool , please comment or approve the PR

**Comment by MaxDesiatov** [comment]
I no longer maintain this library, please avoid tagging me in PRs or issues I don't work on. Thanks!

**Comment by Alkenso** [comment]
@Joannis , maybe you could take a look?

FYI: some tests are broken because of lack Swift support for codable enums with associated values in old versions of Xcode

File: Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift [hunk 1]
```diff
@@ -85,4 +85,23 @@ final class SimpleChoiceTests: XCTestCase {
         let decoded = try XMLDecoder().decode([[IntOrString]].self, from: encoded)
         XCTAssertEqual(original, decoded)
     }
+    
+    func testMixedChoice() throws {
+        enum Choice: Equatable, Codable {
```
Comment (Joannis) [inline Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift:90]: I think that the issue is that Xcode 11.x can't yet generate the codable implementation for this type.
We can wrap this test in a compiler directive like `#if compiler` or `#if swift`.

File: Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift [hunk 2]
```diff
@@ -85,4 +85,23 @@ final class SimpleChoiceTests: XCTestCase {
...
+
+        struct Foo: Equatable, Codable {
+            var one = Choice.one
+            var two = Choice.two(10)
+            var three = Choice.three("qq", value: 20)
+        }
+        
+        let original = Foo()
+        let encoded = try XMLEncoder().encode(original, withRootKey: "container")
+        let decoded = try XMLDecoder().decode(Foo.self, from: encoded)
```
Comment (Joannis) [inline Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift:104]: If possible, I'd love a simple test that demonstrates the expected XML output.

**Comment by Joannis** [comment]
Thanks for pinging me @Alkenso , feel free to ping me anytime I overlook a PR or issue.
It's impossible to support a Swift feature that that compiler version itself does not yet support, so you get a free pass there with a compiler directive to let the tests go on.

File: Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift (hunk 1 above)
Comment (Alkenso) [reply Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift:91]: done

File: Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift (hunk 2 above)
Comment (Alkenso) [reply Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift:111]: added output test

**Comment by Alkenso** [comment]
@Joannis  Please re-run failed job

**Comment by Alkenso** [comment]
Looks very strange. Especially that all works fine on newer and older versions.
Maybe something broken on CI? How can I check it?

**Comment by Joannis** [comment]
@Alkenso a previous PR also failed on the same runner, I think this is a CI failure on Xcode 13.1/macOS 11.

**Review by Joannis — APPROVED** [review]
Looks good!
